version: '3.8'

# Services
services:
  # Server service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server_app
    ports:
      - "5000:5000"
    env_file: ./.env
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_DATABASE
      - DB_PORT=$DB_PORT
    depends_on:
      - mongodb

  # Client service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: dev

    container_name: client_app
    ports:
      - "3000:80"
    depends_on:
      - server

  # Database service
  mongodb:
    image: mongo:latest
    container_name: mongodb_server

    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD

    ports:
      - "27017:27017"

    volumes:
      - ./mydata:/data/db

# Volumes define
volumes: 
  mydata: